/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiCronProviderAuditRouteImport } from './routes/api.cron.provider-audit'
import { Route as EventEventIdIndexRouteImport } from './routes/event.$eventId.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronProviderAuditRoute = ApiCronProviderAuditRouteImport.update({
  id: '/api/cron/provider-audit',
  path: '/api/cron/provider-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const EventEventIdIndexRoute = EventEventIdIndexRouteImport.update({
  id: '/event/$eventId/',
  path: '/event/$eventId/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/cron/provider-audit': typeof ApiCronProviderAuditRoute
  '/event/$eventId/': typeof EventEventIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/cron/provider-audit': typeof ApiCronProviderAuditRoute
  '/event/$eventId': typeof EventEventIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/cron/provider-audit': typeof ApiCronProviderAuditRoute
  '/event/$eventId/': typeof EventEventIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/cron/provider-audit' | '/event/$eventId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/cron/provider-audit' | '/event/$eventId'
  id: '__root__' | '/' | '/api/cron/provider-audit' | '/event/$eventId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiCronProviderAuditRoute: typeof ApiCronProviderAuditRoute
  EventEventIdIndexRoute: typeof EventEventIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/provider-audit': {
      id: '/api/cron/provider-audit'
      path: '/api/cron/provider-audit'
      fullPath: '/api/cron/provider-audit'
      preLoaderRoute: typeof ApiCronProviderAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$eventId/': {
      id: '/event/$eventId/'
      path: '/event/$eventId'
      fullPath: '/event/$eventId/'
      preLoaderRoute: typeof EventEventIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiCronProviderAuditRoute: ApiCronProviderAuditRoute,
  EventEventIdIndexRoute: EventEventIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
